# This playbook will install zabbix agents
- name: Install Zabbix agents
  hosts: zabbix-agents
  become: yes
  vars_files:
    - ./variables.yml
  tasks:
  # download zabbix repo
    - name: wget zabbix repo
      get_url:
        url:  https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_6.0+ubuntu22.04_all.deb
        dest: /tmp/zabbix-release_latest_6.0+ubuntu22.04_all.deb

    # install zabbix
    - name: install zabbix
      apt: 
        deb: /tmp/zabbix-release_latest_6.0+ubuntu22.04_all.deb 
        state: present

    # update apt cache
    - name: apt update
      apt: 
        update_cache: yes

    # install zabbix-agent
    - name: install zabbix-agent
      apt: 
        name: zabbix-agent 
        state: present

    # start zabbix agent
    - name: start zabbix agent
      systemd:
        name: zabbix-agent
        state: started
        enabled: yes

    # modify zabbix agent config
    - name: set zabbix agent config
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: 'Server={{ zabbix_server }}'
        state: present
        backup: yes

    # restart apache2 to apply changes
    - name: restart zabbix-agent
      systemd:
        name: zabbix-agent
        state: restarted
        enabled: yes

