# This playbook will install Elasticsearch
- name: Install Elasticsearch
  hosts: elastic-server
  become: yes
  vars_files:
    - ./variables.yml
  tasks:
  # установка зависимостей
  - name: apt update
    apt:  
      update_cache: yes

  - name: install gnupg
    apt: 
      name: gnupg 
      state: present
  
  - name: install apt-transport-https
    apt: 
      name: apt-transport-https 
      state: present
  
  # download Elasticsearch
  - name: wget Elasticsearch
    get_url:
      url: https://mirror.yandex.ru/mirrors/elastic/8/pool/main/e/elasticsearch/elasticsearch-8.19.0-amd64.deb
      dest: /tmp/elasticsearch-8.19.0-amd64.deb

  # install Elasticsearch
  - name: install Elasticsearch
    apt: deb=/tmp/elasticsearch-8.19.0-amd64.deb state=present
    
  - name: Reload service systemd
    systemd:
      daemon_reload: yes

  # start Elasticsearch server
  - name: Start Elasticsearch Server
    systemd:
      name: elasticsearch
      state: started
      enabled: yes

   # modify Elastic server config
  - name: set network.host
    lineinfile:
      path: /etc/elasticsearch/elasticsearch.yml
      regexp: 'network.host:'
      line: 'network.host: 0.0.0.0'
      state: present
  
  - name: set security
    lineinfile:
      path: /etc/elasticsearch/elasticsearch.yml
      regexp: 'xpack.security.enabled:'
      line: 'xpack.security.enabled: false'
      state: present
  
  - name: set discovery.seed_hosts
    lineinfile:
      path: /etc/elasticsearch/elasticsearch.yml
      regexp: 'discovery.seed_hosts:'
      line: 'discovery.seed_hosts: []'
      state: present
  
  # restart Elastic server to apply changes
  - name: restart elastic
    systemd:
      name: elasticsearch
      state: restarted
      enabled: yes
