# This playbook will install web servers
- name: Install web servers
  hosts: webservers
  become: true
  vars_files:
    - ./variables.yml
  tasks:
    - name: Run the equivalent of "apt update" as a separate step
      apt: 
        update_cache: yes
    
    - name: Install latest version of nginx
      apt:  
        name: nginx 
        state: latest
    
    - name: Autostart nginx
      service:
        name: nginx
        enabled: yes
        state: started
    
    - name: Copy new start page to web-server
      copy:
        src: index.html
        dest: /var/www/html/index.html
    
    # restart nginx to apply changes
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes
