# This playbook will install Filebeat
- name: Install Filebeat
  hosts: webservers
  become: yes
  vars_files:
    - ./variables.yml
  tasks:
  # установка зависимостей
  - name: apt update
    apt:  
      update_cache: yes

  - name: install gnupg
    apt: 
      name: gnupg 
      state: present
  
  - name: install apt-transport-https
    apt: 
      name: apt-transport-https 
      state: present
 
  # download filebeat
  - name: wget filebeat
    get_url:
      url: https://mirror.yandex.ru/mirrors/elastic/8/pool/main/f/filebeat/filebeat-8.19.0-amd64.deb
      dest: /tmp/filebeat-8.19.0-amd64.deb

  # install filebeat
  - name: install filebeat
    apt: 
      deb: /tmp/filebeat-8.19.0-amd64.deb 
      state: present

  - name: apt update
    apt:  
      update_cache: yes

  - name: Reload service systemd
    systemd:
      daemon_reload: yes

  # Enable the Nginx module in Filebeat.
  - name: Enable the Nginx module
    shell: sudo filebeat modules enable nginx

  - name: Copy new config file
    copy:
      src: filebeat-nginx.yml
      dest: /etc/filebeat/modules.d/nginx.yml
  
  # Edit filebeat configuration
  
  # Edit modules parameters
  - name: Edit reload.enabled
    lineinfile:
      path: /etc/filebeat/filebeat.yml
      regexp: '^  reload.enabled:'
      line: '  reload.enabled: true'
      state: present

  - name: Edit reload.period
    lineinfile:
      path: /etc/filebeat/filebeat.yml
      regexp: 'reload.period'
      line: '  reload.period: 30s'
      state: present
        
  - name: Remove old Kibana
    blockinfile:
      path: /etc/filebeat/filebeat.yml
      block: |
        # =================================== Kibana ===================================

        # Starting with Beats version 6.0.0, the dashboards are loaded via the Kibana API.
        # This requires a Kibana endpoint configuration.
        setup.kibana:

          # Kibana Host
          # Scheme and port can be left out and will be set to the default (http and 5601)
          # In case you specify and additional path, the scheme is required: http://localhost:5601/path
          # IPv6 addresses should always be defined as: https://[2001:db8::1]:5601
          #host: "localhost:5601"

          # Kibana Space ID
          # ID of the Kibana Space into which the dashboards should be loaded. By default,
          # the Default Space will be used.
          #space.id:
      state: absent 

  - name: Insert new Kibana
    blockinfile:
      path: /etc/filebeat/filebeat.yml
      block: |
        # =================================== Kibana ===================================

        # Starting with Beats version 6.0.0, the dashboards are loaded via the Kibana API.
        # This requires a Kibana endpoint configuration.
        setup.kibana:

          # Kibana Host
          # Scheme and port can be left out and will be set to the default (http and 5601)
          # In case you specify and additional path, the scheme is required: http://localhost:5601/path
          # IPv6 addresses should always be defined as: https://[2001:db8::1]:5601
          host: "{{ kibana_server }}:5601"

          # Kibana Space ID
          # ID of the Kibana Space into which the dashboards should be loaded. By default,
          # the Default Space will be used.
          #space.id:

      marker: "## {mark} kibana host"

  - name: Remove old Elasticsearch Output
    blockinfile:
      path: /etc/filebeat/filebeat.yml
      block: |
        # ---------------------------- Elasticsearch Output ----------------------------
        output.elasticsearch:
          # Array of hosts to connect to.
          #hosts: ["localhost:9200"]

          # Performance preset - one of "balanced", "throughput", "scale",
          # "latency", or "custom".
          preset: balanced
        
          # Protocol - either `http` (default) or `https`.
          #protocol: "https"

          # Authentication credentials - either API key or username/password.
          #api_key: "id:api_key"
          #username: "elastic"
          #password: "changeme"
      state: absent
  
  - name: Insert new Elasticsearch Output
    blockinfile:
      path: /etc/filebeat/filebeat.yml
      block: |
        # ---------------------------- Elasticsearch Output ----------------------------
        output.elasticsearch:
          # Array of hosts to connect to.
          hosts: ["{{ elastic_server }}:9200"]
          
          # Performance preset - one of "balanced", "throughput", "scale",
          # "latency", or "custom".
          preset: balanced

          # Protocol - either `http` (default) or `https`.
          #protocol: "https"

          # Authentication credentials - either API key or username/password.
          #api_key: "id:api_key"
          #username: "elastic"
          #password: "changeme"
      marker: "## {mark} output.elasticsearch"
  
  # Test and apply changes
  - name: Test the configuration
    shell: sudo filebeat test config

  - name: Apply Filebeat setup changes
    shell: sudo filebeat setup
       
  # start filebeat 
  - name: start filebeat
    systemd:
      name: filebeat
      state: started
      enabled: yes
